---
dataset_dir: /data/home/Kunzhe_Huang/dataset/cifar-10/cifar-10-batches-py
saved_dir: ./saved_data
storage_dir: ./storage
batch_size: 128
num_epochs: 200
optimizer:
  SGD:
    weight_decay: 2.e-4
    momentum: 0.9
    lr: 0.1
lr_scheduler:
  MultiStepLR:
    milestones: [100, 150]
    gamma: 0.1